/* Generated by background_scripts/fetch_references.py - do not edit.
 * Citation metadata from Crossref; PDB primary citations from RCSB.
 * Regenerate with: python3 background_scripts/update_database.py
 */
const REFERENCE_DATA = {
 "10.1002/1873-3468.13190": {
  "authors": [
   "Pande S",
   "Bizilj W",
   "Guo H"
  ],
  "year": "2018",
  "journal": "FEBS Letters",
  "volume": "592",
  "page": "2550-2561",
  "title": "Biochemical and structural insights into an allelic variant causing the lysosomal storage disorder – aspartylglucosaminuria"
 },
 "10.1002/bab.2127": {
  "authors": [
   "da Silva LS",
   "Doonan LB",
   "Pessoa A",
   "de Oliveira MA",
   "Long PF"
  ],
  "year": "2022",
  "journal": "Biotechnology and Applied Biochemistry",
  "volume": "69",
  "page": "503-513",
  "title": "Structural and functional diversity of asparaginases: Overview and recommendations for a revised nomenclature"
 },
 "10.1002/jobm.201300741": {
  "authors": [
   "Hong S",
   "Lee Y",
   "Khan AR",
   "Ullah I",
   "Lee C",
   "Park CK",
   "Shin J"
  ],
  "year": "2014",
  "journal": "Journal of Basic Microbiology",
  "volume": "54",
  "page": "500-508",
  "title": "Cloning, expression, and characterization of thermophilic L‐asparaginase from Thermococcus kodakarensis KOD1"
 },
 "10.1002/pro.4920": {
  "authors": [
   "Zhang D",
   "Czapinska H",
   "Bochtler M",
   "Wlodawer A",
   "Lubkowski J"
  ],
  "year": "2024",
  "journal": "Protein Science",
  "volume": "33",
  "page": "",
  "title": "RrA, an enzyme from Rhodospirillum rubrum, is a prototype of a new family of short‐chain L‐asparaginases"
 },
 "10.1002/pro.5560070327": {
  "authors": [
   "Xuan J",
   "Tarentino AL",
   "Grimwood BG",
   "Plummer TH",
   "Roey PV",
   "Cui T",
   "Guan C"
  ],
  "year": "1998",
  "journal": "Protein Science",
  "volume": "7",
  "page": "774-781",
  "title": "Crystal structure of glycosylasparaginase from Flavobacterium meningosepticum"
 },
 "10.1007/s00253-017-8456-5": {
  "authors": [
   "Ghasemi A",
   "Asad S",
   "Kabiri M",
   "Dabirmanesh B"
  ],
  "year": "2017",
  "journal": "Applied Microbiology and Biotechnology",
  "volume": "101",
  "page": "7227-7238",
  "title": "Cloning and characterization of Halomonas elongata L-asparaginase, a promising chemotherapeutic agent"
 },
 "10.1007/s00253-019-09967-w": {
  "authors": [
   "Li X",
   "Zhang X",
   "Xu S",
   "Xu M",
   "Yang T",
   "Wang L",
   "Zhang H",
   "Fang H",
   "Osire T",
   "Rao Z"
  ],
  "year": "2019",
  "journal": "Applied Microbiology and Biotechnology",
  "volume": "103",
  "page": "7055-7070",
  "title": "Insight into the thermostability of thermophilic L-asparaginase and non-thermophilic L-asparaginase II through bioinformatics and structural analysis"
 },
 "10.1007/s00253-022-11954-7": {
  "authors": [
   "Johny TK",
   "Puthusseri RM",
   "Saidumohamed BE",
   "Sheela UB",
   "Puthusseri SP",
   "Sasidharan RS",
   "Bhat SG"
  ],
  "year": "2022",
  "journal": "Applied Microbiology and Biotechnology",
  "volume": "106",
  "page": "3583-3598",
  "title": "Appraisal of cytotoxicity and acrylamide mitigation potential of L-asparaginase SlpA from fish gut microbiome"
 },
 "10.1007/s00449-014-1277-3": {
  "authors": [
   "Meena B",
   "Anburajan L",
   "Dheenan PS",
   "Begum M",
   "Vinithkumar NV",
   "Dharani G",
   "Kirubagaran R"
  ],
  "year": "2015",
  "journal": "Bioprocess and Biosystems Engineering",
  "volume": "38",
  "page": "373-388",
  "title": "Novel glutaminase free l-asparaginase from Nocardiopsis alba NIOT-VKMA08: production, optimization, functional and molecular characterization"
 },
 "10.1007/s00449-022-02769-x": {
  "authors": [
   "Bento HBS",
   "Paiva GB",
   "Almeida MR",
   "Silva CG",
   "Carvalho PJ",
   "Tavares APM",
   "Pedrolli DB",
   "Santos-Ebinuma VC"
  ],
  "year": "2022",
  "journal": "Bioprocess and Biosystems Engineering",
  "volume": "45",
  "page": "1635-1644",
  "title": "Aliivibrio fischeri L-Asparaginase production by engineered Bacillus subtilis: a potential new biopharmaceutical"
 },
 "10.1007/s00792-015-0763-0": {
  "authors": [
   "Zuo S",
   "Zhang T",
   "Jiang B",
   "Mu W"
  ],
  "year": "2015",
  "journal": "Extremophiles",
  "volume": "19",
  "page": "841-851",
  "title": "Reduction of acrylamide level through blanching with treatment by an extremely thermostable l-asparaginase during French fries processing"
 },
 "10.1007/s10123-024-00493-y": {
  "authors": [
   "Sundaram SS",
   "Kannan A",
   "Chintaluri PG",
   "Sreekala AGV",
   "Nathan VK"
  ],
  "year": "2024",
  "journal": "International Microbiology",
  "volume": "27",
  "page": "1765-1779",
  "title": "Thermostable bacterial L-asparaginase for polyacrylamide inhibition and in silico mutational analysis"
 },
 "10.1007/s10126-022-10129-9": {
  "authors": [
   "Izadpanah Qeshmi F",
   "Homaei A",
   "Khajeh K",
   "Kamrani E",
   "Fernandes P"
  ],
  "year": "2022",
  "journal": "Marine Biotechnology",
  "volume": "24",
  "page": "599-613",
  "title": "Production of a Novel Marine Pseudomonas aeruginosa Recombinant L-Asparaginase: Insight on the Structure and Biochemical Characterization"
 },
 "10.1007/s10482-015-0614-0": {
  "authors": [
   "Sun Z",
   "Li D",
   "Liu P",
   "Wang W",
   "Ji K",
   "Huang Y",
   "Cui Z"
  ],
  "year": "2016",
  "journal": "Antonie van Leeuwenhoek",
  "volume": "109",
  "page": "121-130",
  "title": "A novel l-asparaginase from Aquabacterium sp. A7-Y with self-cleavage activation"
 },
 "10.1007/s10529-017-2470-7": {
  "authors": [
   "Arjun JK",
   "Aneesh BP",
   "Kavitha T",
   "Harikrishnan K"
  ],
  "year": "2018",
  "journal": "Biotechnology Letters",
  "volume": "40",
  "page": "343-348",
  "title": "Characterization of a novel asparaginase from soil metagenomic libraries generated from forest soil"
 },
 "10.1007/s10930-020-09932-x": {
  "authors": [
   "Aly N",
   "El-Ahwany A",
   "Ataya FS",
   "Saeed H"
  ],
  "year": "2020",
  "journal": "The Protein Journal",
  "volume": "39",
  "page": "717-729",
  "title": "Bacillus sonorensis L. Asparaginase: Cloning, Expression in E. coli and Characterization"
 },
 "10.1007/s11274-012-1213-0": {
  "authors": [
   "Mohan Kumar NS",
   "Manonmani HK"
  ],
  "year": "2013",
  "journal": "World Journal of Microbiology and Biotechnology",
  "volume": "29",
  "page": "577-587",
  "title": "Purification, characterization and kinetic properties of extracellular l-asparaginase produced by Cladosporium sp."
 },
 "10.1007/s11756-024-01624-6": {
  "authors": [
   "Kumar V",
   "Darnal S",
   "Patial V",
   "Kumar S",
   "Thakur V",
   "Kumar V",
   "Singh D"
  ],
  "year": "2024",
  "journal": "Biologia",
  "volume": "79",
  "page": "1525-1537",
  "title": "Biochemical characterization of genome derived L-asparaginase from eurypsychrophilic Iodobacter sp. PCH194 for therapeutic and food applications"
 },
 "10.1007/s12010-014-1200-z": {
  "authors": [
   "Sudhir AP",
   "Dave BR",
   "Prajapati AS",
   "Panchal K",
   "Patel D",
   "Subramanian RB"
  ],
  "year": "2014",
  "journal": "Applied Biochemistry and Biotechnology",
  "volume": "174",
  "page": "2504-2515",
  "title": "Characterization of a Recombinant Glutaminase-Free l-Asparaginase (ansA3) Enzyme with High Catalytic Activity from Bacillus licheniformis"
 },
 "10.1007/s12010-023-04715-3": {
  "authors": [
   "Zhang W",
   "Dai Q",
   "Huang Z",
   "Xu W"
  ],
  "year": "2024",
  "journal": "Applied Biochemistry and Biotechnology",
  "volume": "196",
  "page": "3387-3401",
  "title": "Identification and Thermostability Modification of the Mesophilic L-asparaginase from Limosilactobacillus secaliphilus"
 },
 "10.1007/s12033-014-9766-9": {
  "authors": [
   "Gervais D",
   "Foote N"
  ],
  "year": "2014",
  "journal": "Molecular Biotechnology",
  "volume": "56",
  "page": "865-877",
  "title": "Recombinant Deamidated Mutants of Erwinia chrysanthemi l-Asparaginase Have Similar or Increased Activity Compared to Wild-Type Enzyme"
 },
 "10.1007/s12033-014-9819-0": {
  "authors": [
   "Pokrovskaya MV",
   "Aleksandrova SS",
   "Pokrovsky VS",
   "Veselovsky AV",
   "Grishin DV",
   "Abakumova OY",
   "Podobed OV",
   "Mishin AA",
   "Zhdanov DD",
   "Sokolov NN"
  ],
  "year": "2015",
  "journal": "Molecular Biotechnology",
  "volume": "57",
  "page": "251-264",
  "title": "Identification of Functional Regions in the Rhodospirillum rubrum l-Asparaginase by Site-Directed Mutagenesis"
 },
 "10.1007/s12088-019-00806-0": {
  "authors": [
   "Aishwarya SS",
   "Selvarajan E",
   "Iyappan S",
   "Rajnish KN"
  ],
  "year": "2019",
  "journal": "Indian Journal of Microbiology",
  "volume": "59",
  "page": "313-320",
  "title": "Recombinant l-Asparaginase II from Lactobacillus casei subsp. casei ATCC 393 and Its Anticancer Activity"
 },
 "10.1007/s12223-018-0656-6": {
  "authors": [
   "Chohan SM",
   "Rashid N",
   "Sajed M",
   "Imanaka T"
  ],
  "year": "2019",
  "journal": "Folia Microbiologica",
  "volume": "64",
  "page": "313-320",
  "title": "Pcal_0970: an extremely thermostable l-asparaginase from Pyrobaculum calidifontis with no detectable glutaminase activity"
 },
 "10.1007/s13205-017-0974-4": {
  "authors": [
   "Susan Aishwarya S",
   "Iyappan S",
   "Vijaya Lakshmi K",
   "Rajnish KN"
  ],
  "year": "2017",
  "journal": "3 Biotech",
  "volume": "7",
  "page": "",
  "title": "In silico analysis, molecular cloning, expression and characterization of l-asparaginase gene from Lactobacillus reuteri DSM 20016"
 },
 "10.1007/s13205-022-03224-0": {
  "authors": [
   "Kumar S",
   "Darnal S",
   "Patial V",
   "Kumar V",
   "Kumar V",
   "Kumar S",
   "Singh D"
  ],
  "year": "2022",
  "journal": "3 Biotech",
  "volume": "12",
  "page": "",
  "title": "Molecular cloning, characterization, and in-silico analysis of l-asparaginase from Himalayan Pseudomonas sp. PCH44"
 },
 "10.1016/S0014-5793(97)00761-8": {
  "authors": [
   "Noronkoski T",
   "Stoineva IB",
   "Petkov DD",
   "Mononen I"
  ],
  "year": "1997",
  "journal": "FEBS Letters",
  "volume": "412",
  "page": "149-152",
  "title": "Recombinant human glycosylasparaginase catalyzes hydrolysis of l‐asparagine"
 },
 "10.1016/j.bej.2023.108806": {
  "authors": [
   "Yilmazer Aktar B",
   "Georgakis N",
   "Labrou N",
   "Turunen O",
   "Binay B"
  ],
  "year": "2023",
  "journal": "Biochemical Engineering Journal",
  "volume": "191",
  "page": "108806",
  "title": "Comparative structural and kinetic study for development of a novel candidate L-asparaginase based pharmaceutical"
 },
 "10.1016/j.biochi.2020.12.023": {
  "authors": [
   "Kataria A",
   "Patel AK",
   "Kundu B"
  ],
  "year": "2021",
  "journal": "Biochimie",
  "volume": "182",
  "page": "1-12",
  "title": "Distinct functional properties of secretory l-asparaginase Rv1538c involved in phagosomal survival of Mycobacterium tuberculosis"
 },
 "10.1016/j.biochi.2025.03.003": {
  "authors": [
   "Natanzi SsM",
   "Asad S",
   "Mahboudi H",
   "Eslami S"
  ],
  "year": "2025",
  "journal": "Biochimie",
  "volume": "233",
  "page": "122-131",
  "title": "Cloning, Expression, Characterization and in silico studies of l-asparaginase from Vibrio sp. (GBPx3)"
 },
 "10.1016/j.ijbiomac.2016.11.115": {
  "authors": [
   "Shi R",
   "Liu Y",
   "Mu Q",
   "Jiang Z",
   "Yang S"
  ],
  "year": "2017",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "96",
  "page": "93-99",
  "title": "Biochemical characterization of a novel L-asparaginase from Paenibacillus barengoltzii being suitable for acrylamide reduction in potato chips and mooncakes"
 },
 "10.1016/j.ijbiomac.2017.12.165": {
  "authors": [
   "Radha R",
   "Arumugam N",
   "Gummadi SN"
  ],
  "year": "2018",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "111",
  "page": "129-138",
  "title": "Glutaminase free l-asparaginase from Vibrio cholerae: Heterologous expression, purification and biochemical characterization"
 },
 "10.1016/j.ijbiomac.2019.10.258": {
  "authors": [
   "Farahat MG",
   "Amr D",
   "Galal A"
  ],
  "year": "2020",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "143",
  "page": "685-695",
  "title": "Molecular cloning, structural modeling and characterization of a novel glutaminase-free L-asparaginase from Cobetia amphilecti AMI6"
 },
 "10.1016/j.ijbiomac.2020.01.012": {
  "authors": [
   "Chohan SM",
   "Sajed M",
   "Naeem Su",
   "Rashid N"
  ],
  "year": "2020",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "147",
  "page": "131-137",
  "title": "Heterologous gene expression and characterization of TK2246, a highly active and thermostable plant type l-asparaginase from Thermococcus kodakarensis"
 },
 "10.1016/j.ijbiomac.2022.06.110": {
  "authors": [
   "Chakravarty N",
   "Sharma M",
   "Kumar P",
   "Singh R"
  ],
  "year": "2022",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "215",
  "page": "1-11",
  "title": "Biochemical and molecular insights on the bioactivity and binding interactions of Bacillus australimaris NJB19 L-asparaginase"
 },
 "10.1016/j.ijbiomac.2024.130438": {
  "authors": [
   "Sania A",
   "Muhammad MA",
   "Sajed M",
   "Azim N",
   "Ahmad N",
   "Aslam M",
   "Tang XF",
   "Rashid N"
  ],
  "year": "2024",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "263",
  "page": "130438",
  "title": "Structural and functional analyses of an L-asparaginase from Geobacillus thermopakistaniensis"
 },
 "10.1016/j.ijbiomac.2024.135458": {
  "authors": [
   "Abdullah EM",
   "Khan MS",
   "Aziz IM",
   "Alokail MS",
   "Karthikeyan S",
   "Rupavarshini M",
   "Bhat SA",
   "Ataya FS"
  ],
  "year": "2024",
  "journal": "International Journal of Biological Macromolecules",
  "volume": "279",
  "page": "135458",
  "title": "Expression, characterization and cytotoxicity of recombinant l-asparaginase II from Salmonella paratyphi cloned in Escherichia coli"
 },
 "10.1016/j.jbiosc.2013.04.005": {
  "authors": [
   "Chohan SM",
   "Rashid N"
  ],
  "year": "2013",
  "journal": "Journal of Bioscience and Bioengineering",
  "volume": "116",
  "page": "438-443",
  "title": "TK1656, a thermostable l-asparaginase from Thermococcus kodakaraensis, exhibiting highest ever reported enzyme activity"
 },
 "10.1016/j.jbiosc.2018.09.007": {
  "authors": [
   "Feng Y",
   "Liu S",
   "Jiao Y",
   "Wang Y",
   "Wang M",
   "Du G"
  ],
  "year": "2019",
  "journal": "Journal of Bioscience and Bioengineering",
  "volume": "127",
  "page": "418-424",
  "title": "Gene cloning and expression of the l-asparaginase from Bacillus cereus BDRD-ST26 in Bacillus subtilis WB600"
 },
 "10.1016/j.jmb.2006.04.066": {
  "authors": [
   "Michalska K",
   "Bujacz G",
   "Jaskolski M"
  ],
  "year": "2006",
  "journal": "Journal of Molecular Biology",
  "volume": "360",
  "page": "105-116",
  "title": "Crystal Structure of Plant Asparaginase"
 },
 "10.1016/j.jmb.2007.03.061": {
  "authors": [
   "Yun MK",
   "Nourse A",
   "White SW",
   "Rock CO",
   "Heath RJ"
  ],
  "year": "2007",
  "journal": "Journal of Molecular Biology",
  "volume": "369",
  "page": "794-811",
  "title": "Crystal Structure and Allosteric Regulation of the Cytoplasmic Escherichia coli l-Asparaginase I"
 },
 "10.1016/j.pep.2011.12.005": {
  "authors": [
   "Pokrovskaya M",
   "Aleksandrova S",
   "Pokrovsky V",
   "Omeljanjuk N",
   "Borisova A",
   "Anisimova N",
   "Sokolov N"
  ],
  "year": "2012",
  "journal": "Protein Expression and Purification",
  "volume": "82",
  "page": "150-154",
  "title": "Cloning, expression and characterization of the recombinant Yersinia pseudotuberculosis l-asparaginase"
 },
 "10.1016/j.pep.2022.106146": {
  "authors": [
   "Özdemir Fİ",
   "Didem Orhan M",
   "Atasavum ZT",
   "Tülek A"
  ],
  "year": "2022",
  "journal": "Protein Expression and Purification",
  "volume": "199",
  "page": "106146",
  "title": "Biochemical characterization and detection of antitumor activity of l-asparaginase from thermophilic Geobacillus kaustophilus DSM 7263T"
 },
 "10.1016/j.str.2005.06.016": {
  "authors": [
   "Schmitt E",
   "Panvert M",
   "Blanquet S",
   "Mechulam Y"
  ],
  "year": "2005",
  "journal": "Structure",
  "volume": "13",
  "page": "1421-1433",
  "title": "Structural Basis for tRNA-Dependent Amidotransferase Function"
 },
 "10.1016/j.str.2021.03.008": {
  "authors": [
   "Nagaratnam N",
   "Delker SL",
   "Jernigan R",
   "Edwards TE",
   "Snider J",
   "Thifault D",
   "Williams D",
   "Nannenga BL",
   "Stofega M",
   "Sambucetti L",
   "Hsieh JJ",
   "Flint AJ",
   "Fromme P",
   "Martin-Garcia JM"
  ],
  "year": "2021",
  "journal": "Structure",
  "volume": "29",
  "page": "873-885.e5",
  "title": "Structural insights into the function of the catalytically active human Taspase1"
 },
 "10.1016/s0021-9258(17)38144-9": {
  "authors": [
   "Dunlop P",
   "Meyer G",
   "Ban D",
   "Roon R"
  ],
  "year": "1978",
  "journal": "Journal of Biological Chemistry",
  "volume": "253",
  "page": "1297-1304",
  "title": "Characterization of two forms of asparaginase in Saccharomyces cerevisiae"
 },
 "10.1021/acs.biochem.5b01157": {
  "authors": [
   "Li W",
   "Irani S",
   "Crutchfield A",
   "Hodge K",
   "Matthews W",
   "Patel P",
   "Zhang YJ",
   "Stone E"
  ],
  "year": "2016",
  "journal": "Biochemistry",
  "volume": "55",
  "page": "960-969",
  "title": "Intramolecular Cleavage of the hASRGL1 Homodimer Occurs in Two Stages"
 },
 "10.1021/acs.biochem.5b01351": {
  "authors": [
   "Nguyen HA",
   "Su Y",
   "Lavie A"
  ],
  "year": "2016",
  "journal": "Biochemistry",
  "volume": "55",
  "page": "1246-1253",
  "title": "Structural Insight into Substrate Selectivity of Erwinia chrysanthemi l-Asparaginase"
 },
 "10.1021/acs.jafc.0c06609": {
  "authors": [
   "Ran T",
   "Jiao L",
   "Wang W",
   "Chen J",
   "Chi H",
   "Lu Z",
   "Zhang C",
   "Xu D",
   "Lu F"
  ],
  "year": "2021",
  "journal": "Journal of Agricultural and Food Chemistry",
  "volume": "69",
  "page": "223-231",
  "title": "Structures of l-asparaginase from Bacillus licheniformis Reveal an Essential Residue for its Substrate Stereoselectivity"
 },
 "10.1021/acs.jafc.2c05712": {
  "authors": [
   "Chi H",
   "Wang Y",
   "Xia B",
   "Zhou Y",
   "Lu Z",
   "Lu F",
   "Zhu P"
  ],
  "year": "2022",
  "journal": "Journal of Agricultural and Food Chemistry",
  "volume": "70",
  "page": "14499-14509",
  "title": "Enhanced Thermostability and Molecular Insights for l-Asparaginase from Bacillus licheniformis via Structure- and Computation-Based Rational Design"
 },
 "10.1021/acsomega.2c01127": {
  "authors": [
   "Sharma A",
   "Kaushik V",
   "Goel M"
  ],
  "year": "2022",
  "journal": "ACS Omega",
  "volume": "7",
  "page": "40750-40765",
  "title": "Insights into the Distribution and Functional Properties of l-Asparaginase in the Archaeal Domain and Characterization of Picrophilus torridus Asparaginase Belonging to the Novel Family Asp2like1"
 },
 "10.1021/acsomega.3c07633": {
  "authors": [
   "Khabade SP",
   "Sirigiri DNR",
   "Ram AB"
  ],
  "year": "2024",
  "journal": "ACS Omega",
  "volume": "",
  "page": "",
  "title": "l-Asparaginase from Solanum lycopersicum as a Nutraceutical for Acute Lymphoblastic Leukemia"
 },
 "10.1021/acsomega.4c06459": {
  "authors": [
   "Rezende Corrêa P",
   "Schwarz MGA",
   "Antunes D",
   "Piñero SL",
   "Castro Silva M",
   "Mangabeira Crescêncio M",
   "Guimarães ACR",
   "Degrave WM",
   "Mendonça-Lima L"
  ],
  "year": "2024",
  "journal": "ACS Omega",
  "volume": "",
  "page": "",
  "title": "Characterization of Mycobacterium smegmatis Glutaminase-Free Asparaginase (MSMEG_3173)"
 },
 "10.1021/bi00200a005": {
  "authors": [
   "Lubkowski J",
   "Wlodawer A",
   "Ammon HL",
   "Copeland TD",
   "Swain AL"
  ],
  "year": "1994",
  "journal": "Biochemistry",
  "volume": "33",
  "page": "10257-10265",
  "title": "Structural Characterization of Pseudomonas 7A Glutaminase-Asparaginase"
 },
 "10.1021/bi401692v": {
  "authors": [
   "Schalk AM",
   "Lavie A"
  ],
  "year": "2014",
  "journal": "Biochemistry",
  "volume": "53",
  "page": "2318-2328",
  "title": "Structural and Kinetic Characterization of Guinea Pig l-Asparaginase Type III"
 },
 "10.1021/bi901397h": {
  "authors": [
   "Cantor JR",
   "Stone EM",
   "Chantranupong L",
   "Georgiou G"
  ],
  "year": "2009",
  "journal": "Biochemistry",
  "volume": "48",
  "page": "11026-11031",
  "title": "The Human Asparaginase-like Protein 1 hASRGL1 Is an Ntn Hydrolase with β-Aspartyl Peptidase Activity"
 },
 "10.1038/nsb1295-1102": {
  "authors": [
   "Oinonen C",
   "Tikkanen R",
   "Rouvinen J",
   "Peltonen L"
  ],
  "year": "1995",
  "journal": "Nature Structural &amp; Molecular Biology",
  "volume": "2",
  "page": "1102-1108",
  "title": "Three-dimensional structure of human lysosomal aspartylglucosaminidase"
 },
 "10.1038/s41467-021-27105-x": {
  "authors": [
   "Loch JI",
   "Imiolczyk B",
   "Sliwiak J",
   "Wantuch A",
   "Bejger M",
   "Gilski M",
   "Jaskolski M"
  ],
  "year": "2021",
  "journal": "Nature Communications",
  "volume": "12",
  "page": "",
  "title": "Crystal structures of the elusive Rhizobium etli l-asparaginase reveal a peculiar active site"
 },
 "10.1038/s41598-018-36161-1": {
  "authors": [
   "Shakambari G",
   "Sameer Kumar R",
   "Ashokkumar B",
   "Ganesh V",
   "Vasantha VS",
   "Varalakshmi P"
  ],
  "year": "2018",
  "journal": "Scientific Reports",
  "volume": "8",
  "page": "",
  "title": "Cloning and expression of L-asparaginase from Bacillus tequilensis PV9W and therapeutic efficacy of Solid Lipid Particle formulations against cancer"
 },
 "10.1038/s41598-020-78877-z": {
  "authors": [
   "Sharma P",
   "Tomar R",
   "Yadav SS",
   "Badmalia MD",
   "Nath SK",
   "Ashish",
   "Kundu B"
  ],
  "year": "2020",
  "journal": "Scientific Reports",
  "volume": "10",
  "page": "",
  "title": "Heat induces end to end repetitive association in P. furiosus l-asparaginase which enables its thermophilic property"
 },
 "10.1038/s41598-023-34587-w": {
  "authors": [
   "Sharon I",
   "Schmeing TM"
  ],
  "year": "2023",
  "journal": "Scientific Reports",
  "volume": "13",
  "page": "",
  "title": "Bioinformatics of cyanophycin metabolism genes and characterization of promiscuous isoaspartyl dipeptidases that catalyze the final step of cyanophycin degradation"
 },
 "10.1038/srep36239": {
  "authors": [
   "Costa IM",
   "Schultz L",
   "de Araujo Bianchi Pedra B",
   "Leite MSM",
   "Farsky SHP",
   "de Oliveira MA",
   "Pessoa A",
   "Monteiro G"
  ],
  "year": "2016",
  "journal": "Scientific Reports",
  "volume": "6",
  "page": "",
  "title": "Recombinant L-asparaginase 1 from Saccharomyces cerevisiae: an allosteric enzyme with antineoplastic activity"
 },
 "10.1038/srep41643": {
  "authors": [
   "Nguyen HA",
   "Durden DL",
   "Lavie A"
  ],
  "year": "2017",
  "journal": "Scientific Reports",
  "volume": "7",
  "page": "",
  "title": "The differential ability of asparagine and glutamine in promoting the closed/active enzyme conformation rationalizes the Wolinella succinogenes L-asparaginase substrate specificity"
 },
 "10.1042/BA20030138": {
  "authors": [
   "Krasotkina J",
   "Borisova AA",
   "Gervaziev YV",
   "Sokolov NN"
  ],
  "year": "2004",
  "journal": "Biotechnology and Applied Biochemistry",
  "volume": "39",
  "page": "215-221",
  "title": "One‐step purification and kinetic properties of the recombinant l‐asparaginase from Erwinia carotovora"
 },
 "10.1042/bj3640129": {
  "authors": [
   "HEJAZI M",
   "PIOTUKH K",
   "MATTOW J",
   "DEUTZMANN R",
   "VOLKMER-ENGERT R",
   "LOCKAU W"
  ],
  "year": "2002",
  "journal": "Biochemical Journal",
  "volume": "364",
  "page": "129-136",
  "title": "Isoaspartyl dipeptidase activity of plant-type asparaginases"
 },
 "10.1046/j.1471-4159.2003.01766.x": {
  "authors": [
   "Dieterich DC",
   "Landwehr M",
   "Reissner C",
   "Smalla K",
   "Richter K",
   "Wolf G",
   "Böckers TM",
   "Gundelfinger ED",
   "Kreutz MR"
  ],
  "year": "2003",
  "journal": "Journal of Neurochemistry",
  "volume": "85",
  "page": "1117-1125",
  "title": "Gliap − a novel untypical l‐asparaginase localized to rat brain astrocytes"
 },
 "10.1073/pnas.90.4.1474": {
  "authors": [
   "Swain AL",
   "Jaskólski M",
   "Housset D",
   "Rao JK",
   "Wlodawer A"
  ],
  "year": "1993",
  "journal": "Proceedings of the National Academy of Sciences",
  "volume": "90",
  "page": "1474-1478",
  "title": "Crystal structure of Escherichia coli L-asparaginase, an enzyme used in cancer therapy."
 },
 "10.1074/jbc.M113.545038": {
  "authors": [
   "Karamitros CS",
   "Konrad M"
  ],
  "year": "2014",
  "journal": "Journal of Biological Chemistry",
  "volume": "289",
  "page": "12962-12975",
  "title": "Human 60-kDa Lysophospholipase Contains an N-terminal l-Asparaginase Domain That Is Allosterically Regulated by l-Asparagine"
 },
 "10.1074/jbc.M114.609552": {
  "authors": [
   "Schalk AM",
   "Nguyen HA",
   "Rigouin C",
   "Lavie A"
  ],
  "year": "2014",
  "journal": "Journal of Biological Chemistry",
  "volume": "289",
  "page": "33175-33186",
  "title": "Identification and Structural Analysis of an l-Asparaginase Enzyme from Guinea Pig with Putative Tumor Cell Killing Properties"
 },
 "10.1093/bioinformatics/btm098": {
  "authors": [
   "Suzek BE",
   "Huang H",
   "McGarvey P",
   "Mazumder R",
   "Wu CH"
  ],
  "year": "2007",
  "journal": "Bioinformatics",
  "volume": "23",
  "page": "1282-1288",
  "title": "UniRef: comprehensive and non-redundant UniProt reference clusters"
 },
 "10.1093/database/baag045": {
  "authors": [
   "Štětina M",
   "Křenek A",
   "Tedeschi G",
   "Krása F",
   "Spiwok V",
   "Benešová E"
  ],
  "year": "2026",
  "journal": "Database",
  "volume": "2026",
  "page": "",
  "title": "The Asparaginase Database: a comprehensive resource and classification of l-asparaginases"
 },
 "10.1093/glycob/6.5.527": {
  "authors": [
   "Liu Y",
   "Dunn GS",
   "Aronson NN"
  ],
  "year": "1996",
  "journal": "Glycobiology",
  "volume": "6",
  "page": "527-536",
  "title": "Purification, biochemistry and molecular cloning of an insect glycosylasparaginase from Spodoptera frugiperda"
 },
 "10.1093/jambio/lxae062": {
  "authors": [
   "Lailaja VP",
   "Hari V",
   "Sumithra TG",
   "Anusree VN",
   "Suresh G",
   "Sanil NK",
   "Sharma S.R K",
   "Gopalakrishnan A"
  ],
  "year": "2024",
  "journal": "Journal of Applied Microbiology",
  "volume": "135",
  "page": "",
  "title": "In vitro and in silico analysis unravelled clinically desirable attributes of Bacillus altitudinis L-asparaginase"
 },
 "10.1093/nar/gkad1011": {
  "authors": [
   "Varadi M",
   "Bertoni D",
   "Magana P",
   "Paramval U",
   "Pidruchna I",
   "Radhakrishnan M",
   "Tsenkov M",
   "Nair S",
   "Mirdita M",
   "Yeo J",
   "Kovalevskiy O",
   "Tunyasuvunakool K",
   "Laydon A",
   "Žídek A",
   "Tomlinson H",
   "Hariharan D",
   "Abrahamson J",
   "Green T",
   "Jumper J",
   "Birney E",
   "Steinegger M",
   "Hassabis D",
   "Velankar S"
  ],
  "year": "2024",
  "journal": "Nucleic Acids Research",
  "volume": "52",
  "page": "D368-D375",
  "title": "AlphaFold Protein Structure Database in 2024: providing structure coverage for over 214 million protein sequences"
 },
 "10.1093/nar/gkae1010": {
  "authors": [
   "The UniProt Consortium",
   "Bateman A",
   "Martin MJ",
   "Orchard S",
   "Magrane M",
   "Adesina A",
   "Ahmad S",
   "Bowler-Barnett EH",
   "Bye-A-Jee H",
   "Carpentier D",
   "Denny P",
   "Fan J",
   "Garmiri P",
   "Gonzales LJdC",
   "Hussein A",
   "Ignatchenko A",
   "Insana G",
   "Ishtiaq R",
   "Joshi V",
   "Jyothi D",
   "Kandasaamy S",
   "Lock A",
   "Luciani A",
   "Luo J",
   "Lussi Y",
   "Marin JSM",
   "Raposo P",
   "Rice DL",
   "Santos R",
   "Speretta E",
   "Stephenson J",
   "Totoo P",
   "Tyagi N",
   "Urakova N",
   "Vasudev P",
   "Warner K",
   "Wijerathne S",
   "Yu CWH",
   "Zaru R",
   "Bridge AJ",
   "Aimo L",
   "Argoud-Puy G",
   "Auchincloss AH",
   "Axelsen KB",
   "Bansal P",
   "Baratin D",
   "Batista Neto TM",
   "Blatter MC",
   "Bolleman JT",
   "Boutet E",
   "Breuza L",
   "Gil BC",
   "Casals-Casas C",
   "Echioukh KC",
   "Coudert E",
   "Cuche B",
   "de Castro E",
   "Estreicher A",
   "Famiglietti ML",
   "Feuermann M",
   "Gasteiger E",
   "Gaudet P",
   "Gehant S",
   "Gerritsen V",
   "Gos A",
   "Gruaz N",
   "Hulo C",
   "Hyka-Nouspikel N",
   "Jungo F",
   "Kerhornou A",
   "Mercier PL",
   "Lieberherr D",
   "Masson P",
   "Morgat A",
   "Paesano S",
   "Pedruzzi I",
   "Pilbout S",
   "Pourcel L",
   "Poux S",
   "Pozzato M",
   "Pruess M",
   "Redaschi N",
   "Rivoire C",
   "Sigrist CJA",
   "Sonesson K",
   "Sundaram S",
   "Sveshnikova A",
   "Wu CH",
   "Arighi CN",
   "Chen C",
   "Chen Y",
   "Huang H",
   "Laiho K",
   "Lehvaslaiho M",
   "McGarvey P",
   "Natale DA",
   "Ross K",
   "Vinayaka CR",
   "Wang Y",
   "Zhang J"
  ],
  "year": "2025",
  "journal": "Nucleic Acids Research",
  "volume": "53",
  "page": "D609-D617",
  "title": "UniProt: the Universal Protein Knowledgebase in 2025"
 },
 "10.1093/nar/gkae1091": {
  "authors": [
   "Burley SK",
   "Bhatt R",
   "Bhikadiya C",
   "Bi C",
   "Biester A",
   "Biswas P",
   "Bittrich S",
   "Blaumann S",
   "Brown R",
   "Chao H",
   "Chithari VR",
   "Craig PA",
   "Crichlow GV",
   "Duarte JM",
   "Dutta S",
   "Feng Z",
   "Flatt JW",
   "Ghosh S",
   "Goodsell DS",
   "Green RK",
   "Guranovic V",
   "Henry J",
   "Hudson BP",
   "Joy M",
   "Kaelber JT",
   "Khokhriakov I",
   "Lai JS",
   "Lawson CL",
   "Liang Y",
   "Myers-Turnbull D",
   "Peisach E",
   "Persikova I",
   "Piehl DW",
   "Pingale A",
   "Rose Y",
   "Sagendorf J",
   "Sali A",
   "Segura J",
   "Sekharan M",
   "Shao C",
   "Smith J",
   "Trumbull M",
   "Vallat B",
   "Voigt M",
   "Webb B",
   "Whetstone S",
   "Wu-Wu A",
   "Xing T",
   "Young JY",
   "Zalevsky A",
   "Zardecki C"
  ],
  "year": "2025",
  "journal": "Nucleic Acids Research",
  "volume": "53",
  "page": "D564-D574",
  "title": "Updated resources for exploring experimentally-determined PDB structures and Computed Structure Models at the RCSB Protein Data Bank"
 },
 "10.1107/S0907444904003403": {
  "authors": [
   "Prahl A",
   "Pazgier M",
   "Hejazi M",
   "Lockau W",
   "Lubkowski J"
  ],
  "year": "2004",
  "journal": "Acta Crystallographica Section D Biological Crystallography",
  "volume": "60",
  "page": "1173-1176",
  "title": "Structure of the isoaspartyl peptidase with L-asparaginase activity from Escherichia coli"
 },
 "10.1107/S0907444904032950": {
  "authors": [
   "Yao M",
   "Yasutake Y",
   "Morita H",
   "Tanaka I"
  ],
  "year": "2005",
  "journal": "Acta Crystallographica Section D Biological Crystallography",
  "volume": "61",
  "page": "294-301",
  "title": "Structure of the type I L-asparaginase from the hyperthermophilic archaeon Pyrococcus horikoshii at 2.16 Å resolution"
 },
 "10.1107/S0907444907065766": {
  "authors": [
   "Kravchenko OV",
   "Kislitsin YA",
   "Popov AN",
   "Nikonov SV",
   "Kuranova IP"
  ],
  "year": "2008",
  "journal": "Acta Crystallographica Section D Biological Crystallography",
  "volume": "64",
  "page": "248-256",
  "title": "Three-dimensional structures of L-asparaginase from Erwinia carotovora complexed with aspartate and glutamate"
 },
 "10.1107/S0907444994003446": {
  "authors": [
   "Lubkowski J",
   "Wlodawer A",
   "Housset D",
   "Weber IT",
   "Ammon HL",
   "Murphy KC",
   "Swain AL"
  ],
  "year": "1994",
  "journal": "Acta Crystallographica Section D Biological Crystallography",
  "volume": "50",
  "page": "826-832",
  "title": "Refined crystal structure of Acinetobacter glutaminasificans glutaminase–asparaginase"
 },
 "10.1107/S1399004714008700": {
  "authors": [
   "Bejger M",
   "Imiolczyk B",
   "Clavel D",
   "Gilski M",
   "Pajak A",
   "Marsolais F",
   "Jaskolski M"
  ],
  "year": "2014",
  "journal": "Acta Crystallographica Section D Biological Crystallography",
  "volume": "70",
  "page": "1854-1872",
  "title": "Na+/K+ exchange switches the catalytic apparatus of potassium-dependent plant L-asparaginase"
 },
 "10.1107/S2052252521006011": {
  "authors": [
   "Loch JI",
   "Jaskolski M"
  ],
  "year": "2021",
  "journal": "IUCrJ",
  "volume": "8",
  "page": "514-531",
  "title": "Structural and biophysical aspects of L-asparaginases: a growing family with amazing diversity"
 },
 "10.1107/S2059798317014711": {
  "authors": [
   "Guo J",
   "Coker AR",
   "Wood SP",
   "Cooper JB",
   "Chohan SM",
   "Rashid N",
   "Akhtar M"
  ],
  "year": "2017",
  "journal": "Acta Crystallographica Section D Structural Biology",
  "volume": "73",
  "page": "889-895",
  "title": "Structure and function of the thermostable L-asparaginase from Thermococcus kodakarensis"
 },
 "10.1107/S2059798323005648": {
  "authors": [
   "Loch JI",
   "Worsztynowicz P",
   "Sliwiak J",
   "Grzechowiak M",
   "Imiolczyk B",
   "Pokrywka K",
   "Chwastyk M",
   "Gilski M",
   "Jaskolski M"
  ],
  "year": "2023",
  "journal": "Acta Crystallographica Section D Structural Biology",
  "volume": "79",
  "page": "775-791",
  "title": "Rhizobium etli has two L-asparaginases with low sequence identity but similar structure and catalytic center"
 },
 "10.1110/ps.9.10.2009": {
  "authors": [
   "Derst C",
   "Henseling J",
   "Röhm K"
  ],
  "year": "2000",
  "journal": "Protein Science",
  "volume": "9",
  "page": "2009-2017",
  "title": "Engineering the substrate specificity of Escherichia coli asparaginase II. Selective reduction of glutaminase activity by amino acid replacements at position 248"
 },
 "10.1111/febs.16042": {
  "authors": [
   "Lubkowski J",
   "Wlodawer A"
  ],
  "year": "2021",
  "journal": "The FEBS Journal",
  "volume": "288",
  "page": "4183-4209",
  "title": "Structural and biochemical properties of L‐asparaginase"
 },
 "10.1111/febs.16635": {
  "authors": [
   "Strzelczyk P",
   "Zhang D",
   "Alexandratos J",
   "Piszczek G",
   "Wlodawer A",
   "Lubkowski J"
  ],
  "year": "2023",
  "journal": "The FEBS Journal",
  "volume": "290",
  "page": "780-795",
  "title": "The dimeric form of bacterial l‐asparaginase YpAI is fully active"
 },
 "10.1111/j.1432-1033.1996.0201t.x": {
  "authors": [
   "Lubkowski J",
   "Palm GJ",
   "Gilliland GL",
   "Derst C",
   "Röhm K",
   "Wlodawer A"
  ],
  "year": "1996",
  "journal": "European Journal of Biochemistry",
  "volume": "241",
  "page": "201-207",
  "title": "Crystal Structure and Amino Acid Sequence of Wolinella Succinogenes l‐Asparaginase"
 },
 "10.1111/j.1432-1033.2004.04254.x": {
  "authors": [
   "Borek D",
   "Michalska K",
   "Brzezinski K",
   "Kisiel A",
   "Podkowinski J",
   "Bonthron DT",
   "Krowarsch D",
   "Otlewski J",
   "Jaskolski M"
  ],
  "year": "2004",
  "journal": "European Journal of Biochemistry",
  "volume": "271",
  "page": "3215-3226",
  "title": "Expression, purification and catalytic activity of Lupinus luteus asparagine β‐amidohydrolase and its Escherichia coli homolog"
 },
 "10.1111/j.1742-4658.2009.06910.x": {
  "authors": [
   "Kotzia GA",
   "Labrou NE"
  ],
  "year": "2009",
  "journal": "The FEBS Journal",
  "volume": "276",
  "page": "1750-1761",
  "title": "Engineering thermal stability of l‐asparaginase by in vitro directed evolution"
 },
 "10.1126/science.1128470": {
  "authors": [
   "Oshikane H",
   "Sheppard K",
   "Fukai S",
   "Nakamura Y",
   "Ishitani R",
   "Numata T",
   "Sherrer RL",
   "Feng L",
   "Schmitt E",
   "Panvert M",
   "Blanquet S",
   "Mechulam Y",
   "Söll D",
   "Nureki O"
  ],
  "year": "2006",
  "journal": "Science",
  "volume": "312",
  "page": "1950-1954",
  "title": "Structural Basis of RNA-Dependent Recruitment of Glutamine to the Genetic Code"
 },
 "10.1128/aem.03523-13": {
  "authors": [
   "Huang L",
   "Liu Y",
   "Sun Y",
   "Yan Q",
   "Jiang Z"
  ],
  "year": "2014",
  "journal": "Applied and Environmental Microbiology",
  "volume": "80",
  "page": "1561-1569",
  "title": "Biochemical Characterization of a Novel l-Asparaginase with Low Glutaminase Activity from Rhizomucor miehei and Its Application in Food Safety and Leukemia Treatment"
 },
 "10.1128/jb.118.1.231-241.1974": {
  "authors": [
   "Willis RC",
   "Woolfolk CA"
  ],
  "year": "1974",
  "journal": "Journal of Bacteriology",
  "volume": "118",
  "page": "231-241",
  "title": "Asparagine Utilization in Escherichia coli"
 },
 "10.1134/S000629791610014X": {
  "authors": [
   "Kebeish R",
   "El-Sayed A",
   "Fahmy H",
   "Abdel-Ghany A"
  ],
  "year": "2016",
  "journal": "Biochemistry (Moscow)",
  "volume": "81",
  "page": "1173-1181",
  "title": "Molecular cloning, biochemical characterization, and antitumor properties of a novel L-asparaginase from Synechococcus elongatus PCC6803"
 },
 "10.1134/s0006297910030144": {
  "authors": [
   "Bansal S",
   "Gnaneswari D",
   "Mishra P",
   "Kundu B"
  ],
  "year": "2010",
  "journal": "Biochemistry (Moscow)",
  "volume": "75",
  "page": "375-381",
  "title": "Structural stability and functional analysis of L-asparaginase from Pyrococcus furiosus"
 },
 "10.1371/journal.pone.0117025": {
  "authors": [
   "Maggi M",
   "Chiarelli LR",
   "Valentini G",
   "Scotti C"
  ],
  "year": "2015",
  "journal": "PLOS ONE",
  "volume": "10",
  "page": "e0117025",
  "title": "Engineering of Helicobacter pylori L-Asparaginase: Characterization of Two Functionally Distinct Groups of Mutants"
 },
 "10.1371/journal.pone.0181940": {
  "authors": [
   "Coulette Q",
   "Lemauf S",
   "Colinet D",
   "Prévost G",
   "Anselme C",
   "Poirié M",
   "Gatti JL"
  ],
  "year": "2017",
  "journal": "PLOS ONE",
  "volume": "12",
  "page": "e0181940",
  "title": "Biochemical characterization and comparison of aspartylglucosaminidases secreted in venom of the parasitoid wasps Asobara tabida and Leptopilina heterotoma"
 },
 "10.15171/bi.2019.03": {
  "authors": [
   "Safary A",
   "Moniri R",
   "Hamzeh-Mivehroud M",
   "Dastmalchi S"
  ],
  "year": "2019",
  "journal": "BioImpacts",
  "volume": "9",
  "page": "15-23",
  "title": "Highly efficient novel recombinant L-asparaginase with no glutaminase activity from a new halo-thermotolerant Bacillus strain"
 },
 "10.1590/1519-6984.244735": {
  "authors": [
   "Nadeem MS",
   "Khan JA",
   "Al-Ghamdi MA",
   "Khan MI",
   "Zeyadi MA"
  ],
  "year": "2022",
  "journal": "Brazilian Journal of Biology",
  "volume": "82",
  "page": "",
  "title": "Studies on the recombinant production and anticancer activity of thermostable L- asparaginase I from Pyrococcus abyssi"
 },
 "10.18388/abp.2001_3855": {
  "authors": [
   "Borek D",
   "Jaskólski M"
  ],
  "year": "2001",
  "journal": "Acta Biochimica Polonica",
  "volume": "48",
  "page": "893-902",
  "title": "Sequence analysis of enzymes with asparaginase activity."
 },
 "10.26502/jbb.2642-91280015": {
  "authors": [
   "Phetsri K",
   "Furukawa M",
   "Yamashiro R",
   "Kawamura Y",
   "Hayashi J",
   "Tobe R",
   "Toyotake Y",
   "Wakayama M"
  ],
  "year": "2019",
  "journal": "Journal of Biotechnology and Biomedicine",
  "volume": "02",
  "page": "",
  "title": "Comparative Biochemical Characterization of L-Asparaginases from Four Species of Lactic Acid Bacteria"
 },
 "10.3390/catal13050832": {
  "authors": [
   "Dobryakova N",
   "Zhdanov D",
   "Dumina M",
   "Aleksandrova S",
   "Pokrovskaya M",
   "Genin A",
   "Shishparenok A",
   "Zhgun A",
   "Kudryashova EV"
  ],
  "year": "2023",
  "journal": "Catalysts",
  "volume": "13",
  "page": "832",
  "title": "Thermal Inactivation Mechanism and Structural Features Providing Enhanced Thermal Stability of Hyperthermophilic Thermococcus sibiricus L-Asparaginase in Comparison with Mesophilic and Thermophilic L-Asparaginases"
 },
 "10.3390/foods10112819": {
  "authors": [
   "Chi H",
   "Chen M",
   "Jiao L",
   "Lu Z",
   "Bie X",
   "Zhao H",
   "Lu F"
  ],
  "year": "2021",
  "journal": "Foods",
  "volume": "10",
  "page": "2819",
  "title": "Characterization of a Novel L-Asparaginase from Mycobacterium gordonae with Acrylamide Mitigation Potential"
 },
 "10.4014/jmb.1405.05021": {
  "authors": [
   "Han S",
   "Jung J",
   "Park W"
  ],
  "year": "2014",
  "journal": "Journal of Microbiology and Biotechnology",
  "volume": "24",
  "page": "1096-1104",
  "title": "Biochemical Characterization of L-Asparaginase in NaCl-Tolerant Staphylococcus sp. OJ82 Isolated from Fermented Seafood"
 }
};

const PDB_DOI = {
 "1AGX": "10.1107/S0907444994003446",
 "1APY": "10.1038/nsb1295-1102",
 "1AYY": "10.1002/pro.5560070327",
 "1T3M": "10.1107/S0907444904003403",
 "1WLS": "10.1107/S0907444904032950",
 "1WSA": "10.1111/j.1432-1033.1996.0201t.x",
 "1ZQ1": "10.1016/j.str.2005.06.016",
 "2D6F": "10.1126/science.1128470",
 "2GEZ": "10.1016/j.jmb.2006.04.066",
 "2HIM": "10.1016/j.jmb.2007.03.061",
 "2HLN": "10.1107/S0907444907065766",
 "3ECA": "10.1073/pnas.90.4.1474",
 "3PGA": "10.1021/bi00200a005",
 "4O47": "10.1021/bi401692v",
 "4PU6": "10.1107/S1399004714008700",
 "4R8L": "10.1074/jbc.M114.609552",
 "4ZM9": "10.1021/acs.biochem.5b01157",
 "5CBP": "10.1038/s41598-020-78877-z",
 "5F52": "10.1021/acs.biochem.5b01351",
 "5OT0": "10.1107/S2059798317014711",
 "6DEY": "10.1002/1873-3468.13190",
 "6VIN": "10.1016/j.str.2021.03.008",
 "7CB4": "10.1021/acs.jafc.0c06609",
 "7OS6": "10.1038/s41467-021-27105-x",
 "7R69": "10.1111/febs.16635",
 "8CLZ": "10.1107/S2059798323005648",
 "8DQM": "10.1038/s41598-023-34587-w",
 "8UOO": "10.1002/pro.4920"
};

const SITE_REFERENCES = [
 {
  "doi": "10.1093/database/baag045",
  "group": "database",
  "label": "The Asparaginase Database",
  "note": "The paper to cite when you use this database."
 },
 {
  "doi": "10.1002/bab.2127",
  "group": "prior",
  "label": "Nomenclature and Sequence Analysis",
  "note": ""
 },
 {
  "doi": "10.1107/S2052252521006011",
  "group": "prior",
  "label": "Structural diversity",
  "note": ""
 },
 {
  "doi": "10.1111/febs.16042",
  "group": "prior",
  "label": "Structure and biochemistry",
  "note": ""
 },
 {
  "doi": "10.18388/abp.2001_3855",
  "group": "prior",
  "label": "Sequence analysis",
  "note": ""
 },
 {
  "doi": "10.1093/nar/gkae1010",
  "group": "source",
  "label": "UniProt",
  "note": "Accessions, entry names and annotations."
 },
 {
  "doi": "10.1093/bioinformatics/btm098",
  "group": "source",
  "label": "UniRef100",
  "note": "Licensed under CC BY 4.0. Added classification code to sequence headers."
 },
 {
  "doi": "10.1093/nar/gkad1011",
  "group": "source",
  "label": "AlphaFold",
  "note": "Licensed under CC BY 4.0."
 },
 {
  "doi": "10.1093/nar/gkae1091",
  "group": "source",
  "label": "PDB",
  "note": "Structure entries and the primary publications cited for them. Released to the public domain under CC0 1.0."
 }
];
